server:
  port: 8081
#  servlet:
#    context-path: /itop-api

spring:
  application:
    name: itop-api
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: hugo0129@qq.com
    password: dsxozsdnemngdiha
    from: hugo0129@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #  redis配置
  redis:
    host: 140.143.208.132
    port: 6379
    password: 123456
    timeout: 10
    jedis:
      pool:
        max-idle: 500
        max-wait: 1000
  # 返回的api接口配置
  jackson:
    # 默认某一个字段为NULL，则不返回
    default-property-inclusion: non_null
eureka:
  client:
    # 服务发现地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #是否将自己注册到eureka服务注册中心，默认为true
    register-with-eureka: true
    #是否从服务注册中心获取可用的服务清单，默认为true
    fetch-registry: true
feign:
  # 熔断限流开启
  hystrix:
    enabled: true

# hystrix熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 800000
ribbon:
  ReadTimeout: 800000
  ConnectTimeout: 800000
logging:
  level:
    root:
    com.bund.north.itop.api.clients.user.UserClient: debug
