server:
  port: 8080
#  servlet:
#    context-path: /itop-api

spring:
  application:
    name: itop-api
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: hugo0129@qq.com
    password: dsxozsdnemngdiha
    from: hugo0129@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
eureka:
  client:
    # 服务发现地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #是否将自己注册到eureka服务注册中心，默认为true
    register-with-eureka: true
    #是否从服务注册中心获取可用的服务清单，默认为true
    fetch-registry: true
feign:
  # 熔断限流开启
  hystrix:
    enabled: true

# hystrix熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000
logging:
  level:
    root:
    com.bund.north.itop.api.clients.user.UserClient: debug
