server:
  port: 8080
  servlet:
    context-path: /itop-api

spring:
  application:
    name: itop-api
eureka:
  client:
    # 服务发现地址
    service-url:
      defaultZone: http://localhost:8083/itop-eureka/
    register-with-eureka: false
    fetch-registry: false
ribbon:
  eureka:
    enabled: true