server:
  port: 8083
#  servlet:
#    context-path: /itop-user
# spring相关配置
spring:
  application:
    name: itop-user
  #  数据源配置
  datasource:
    url: jdbc:mysql://140.143.208.132:3306/itop?useUnicode=true&characterEncoding=utf8
    username: root
    password: Hugo2018!
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  mapper-locations: classpath:com/bund/north/itop/user/mapper/*.xml
mybatis-plus:
  type-aliases-package: com.bund.north.itop.user.entity
  #  打印sql日志，建议仅用于开发环境
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#服务注册与发现配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
